export default {
  namespaced: true,
  state() {
    return {
      districts: [
        'Adalar',
        'Arnavutköy',
        'Ataşehir',
        'Avcılar',
        'Bağcılar',
        'Bahçelievler',
        'Bakırköy',
        'Başakşehir',
        'Bayrampaşa',
        'Beşiktaş',
        'Beykoz',
        'Beylikdüzü',
        'Beyoğlu',
        'Büyükçekmece',
        'Çatalca',
        'Çekmeköy',
        'Esenler',
        'Esenyurt',
        'Eyüpsultan',
        'Fatih',
        'Gaziosmanpaşa',
        'Güngören',
        'Istanbul',
        'Kadıköy',
        'Kağıthane',
        'Kartal',
        'Küçükçekmece',
        'Maltepe',
        'Pendik',
        'Sancaktepe',
        'Sarıyer',
        'Silivri',
        'Sultanbeyli',
        'Sultangazi',
        'Şile',
        'Şişli',
        'Tuzla',
        'Ümraniye',
        'Üsküdar',
        'Zeytinburnu',
      ],
      categories: [
        'Electronics',
        'Computers',
        'Smart Home',
        'Arts & Crafts',
        'Automotive',
        'Baby',
        'Beauty and Personal Care',
        "Women's Fashion",
        "Men's Fashion",
        "Girls' Fashion",
        "Boys' Fashion",
        'Health and Household',
        'Home and Kitchen',
        'Industrial and Scientific',
        'Luggage',
        'Movies & Television',
        'Pet Supplies',
        'Software',
        'Sports and Outdoors',
        'Tools & Home Improvement',
        'Toys and Games',
        'Video Games',
      ],
      subCategories: {
        electronics: [
          'Accessories & Supplies',
          'Camera & Photo',
          'Car & Vehicle Electronics',
          'Cell Phones & Accessories',
          'Computers & Accessories',
          'GPS & Navigation',
          'Headphones',
          'Home Audio',
          'Office Electronics',
          'Portable Audio & Video',
          'Security & Surveillance',
          'Service Plans',
          'Television & Video',
          'Video Game Consoles & Accessories',
          'Video Projectors',
          'Wearable Technology',
          'eBook Readers & Accessories',
        ],
        computers: [
          'Computer Accessories & Peripherals',
          'Computer Components',
          'Computers & Tablets',
          'Data Storage',
          'External Components',
          'Laptop Accessories',
          'Monitors',
          'Networking Products',
          'Power Strips & Surge Protectors',
          'Printers',
          'Scanners',
          'Servers',
          'Tablet Accessories',
          'Tablet Replacement Parts',
          'Warranties & Services',
        ],
        smartHome: [
          'Smart Home Lighting',
          'Smart Locks and Entry',
          'Security Cameras and Systems',
          'Plugs and Outlets',
          'New Smart Devices',
          'Heating and Cooling',
          'Detectors and Sensors',
          'Home Entertainment',
          'Pet',
          'Voice Assistants and Hubs',
          'Kitchen',
          'Vacuums and Mops',
          'Lawn and Garden',
          'WIFI and Networking',
          'Other Solutions',
        ],
        artsCrafts: [
          'Painting, Drawing & Art Supplies',
          'Beading & Jewelry Making',
          'Crafting',
          'Fabric',
          'Fabric Decorating',
          'Knitting & Crochet',
          'Needlework',
          'Organization, Storage & Transport',
          'Printmaking',
          'Scrapbooking & Stamping',
          'Sewing',
          'Party Decorations & Supplies',
          'Gift Wrapping Supplies',
        ],
        automotive: [
          'Car Care',
          'Car Electronics & Accessories',
          'Exterior Accessories',
          'Interior Accessories',
          'Lights & Lighting Accessories',
          'Motorcycle & Powersports',
          'Oils & Fluids',
          'Paint & Paint Supplies',
          'Performance Parts & Accessories',
          'Replacement Parts',
          'RV Parts & Accessories',
          'Tires & Wheels',
          'Tools & Equipment',
          'Automotive Enthusiast Merchandise',
          'Heavy Duty & Commercial Vehicle Equipment',
        ],
        baby: [
          'Activity & Entertainment',
          'Apparel & Accessories',
          'Baby & Toddler Toys',
          'Baby Care',
          'Baby Stationery',
          'Car Seats & Accessories',
          'Diapering',
          'Feeding',
          'Gifts',
          'Nursery',
          'Potty Training',
          'Pregnancy & Maternity',
          'Safety',
          'Strollers & Accessories',
          'Travel Gear',
        ],
        beautyandPersonalCare: [
          'Makeup',
          'Skin Care',
          'Hair Care',
          'Fragrance',
          'Foot, Hand & Nail Care',
          'Tools & Accessories',
          'Shave & Hair Removal',
          'Personal Care',
          'Oral Care',
        ],
        womensFashion: [
          'Clothing',
          'Shoes',
          'Jewelry',
          'Watches',
          'Handbags',
          'Accessories',
        ],
        mensFashion: ['Clothing', 'Shoes', 'Watches', 'Accessories'],
        girlsFashion: [
          'Clothing',
          'Shoes',
          'Jewelry',
          'Watches',
          'Accessories',
          'School Uniforms',
        ],
        boysFashion: [
          'Clothing',
          'Shoes',
          'Jewelry',
          'Watches',
          'Accessories',
          'School Uniforms',
        ],
        healthandHousehold: [
          'Baby & Child Care',
          'Health Care',
          'Household Supplies',
          'Medical Supplies & Equipment',
          'Oral Care',
          'Personal Care',
          'Sexual Wellness',
          'Sports Nutrition',
          'Stationery & Gift Wrapping Supplies',
          'Vision Care',
          'Vitamins & Dietary Supplements',
          'Wellness & Relaxation',
        ],
        homeandKitchen: [
          "Kids' Home Store",
          'Kitchen & Dining',
          'Bedding',
          'Bath',
          'Furniture',
          'Home Decor',
          'Wall Art',
          'Lighting & Ceiling Fans',
          'Seasonal Decor',
          'Event & Party Supplies',
          'Heating, Cooling & Air Quality',
          'Irons & Steamers',
          'Vacuums & Floor Care',
          'Storage & Organization',
          'Cleaning Supplies',
        ],
        industrialandScientific: [
          'Abrasive & Finishing Products',
          'Additive Manufacturing Products',
          'Commercial Door Products',
          'Cutting Tools',
          'Fasteners',
          'Filtration',
          'Food Service Equipment & Supplies',
          'Hydraulics, Pneumatics & Plumbing',
          'Industrial Electrical',
          'Industrial Hardware',
          'Industrial Power & Hand Tools',
          'Janitorial & Sanitation Supplies',
          'Lab & Scientific Products',
          'Material Handling Products',
          'Occupational Health & Safety Products',
          'Packaging & Shipping Supplies',
          'Power Transmission Products',
          'Professional Dental Supplies',
          'Professional Medical Supplies',
          'Raw Materials',
          'Retail Store Fixtures & Equipment',
          'Robotics',
          'Science Education',
          'Tapes, Adhesives & Sealants',
          'Test, Measure & Inspect',
        ],
        luggage: [
          'luggage',
          'Carry-ons',
          'Backpacks',
          'Garment bags',
          'Travel Totes',
          'Luggage Sets',
          'Laptop Bags',
          'Suitcases',
          'Kids Luggage',
          'Messenger Bags',
          'Umbrellas',
          'Duffles',
          'Travel Accessories',
        ],
        moviesTelevision: [
          'Movies',
          'TV Shows',
          'Blu-ray',
          '4K Ultra HD',
          'New Releases',
          'Pre-orders',
          'Kids & Family',
          'Prime Video',
        ],
        petSupplies: [
          'Cats',
          'Fish & Aquatic Pets',
          'Birds',
          'Horses',
          'Reptiles & Amphibians',
          'Small Animals',
        ],
        software: [
          'Accounting & Finance',
          'Antivirus & Security',
          'Business & Office',
          "Children's",
          'Design & Illustration',
          'Digital Software',
          'Education & Reference',
          'Games',
          'Lifestyle & Hobbies',
          'Music',
          'Networking & Servers',
          'Operating Systems',
          'Photography',
          'Programming & Web Development',
          'Tax Preparation',
          'Utilities',
          'Video',
        ],
        sportsandOutdoors: [
          'Sports and Outdoors',
          'Outdoor Recreation',
          'Sports & Fitness',
          'Fan Shop',
        ],
        toolsHomeImprovement: [
          'Tools & Home Improvement',
          'Appliances',
          'Building Supplies',
          'Electrical',
          'Hardware',
          'Kitchen & Bath Fixtures',
          'Light Bulbs',
          'Lighting & Ceiling Fans',
          'Measuring & Layout Tools',
          'Painting Supplies & Wall Treatments',
          'Power & Hand Tools',
          'Rough Plumbing',
          'Safety & Security',
          'Storage & Home Organization',
          'Welding & Soldering',
        ],
        toysandGames: [
          'Action Figures & Statues',
          'Arts & Crafts',
          'Baby & Toddler Toys',
          'Building Toys',
          'Dolls & Accessories',
          'Dress Up & Pretend Play',
          "Kids' Electronics",
          'Games',
          'Grown-Up Toys',
          'Hobbies',
          "Kids' Furniture, DÃ©cor & Storage",
          'Learning & Education',
          'Novelty & Gag Toys',
          'Party Supplies',
          'Puppets',
          'Puzzles',
          'Sports & Outdoor Play',
          'Stuffed Animals & Plush Toys',
          'Toy Remote Control & Play Vehicles',
          'Tricycles, Scooters & Wagons',
          'Video Games',
        ],
        videoGames: [
          'Video Games',
          'PlayStation 4',
          'PlayStation 3',
          'Xbox One',
          'Xbox 360',
          'Nintendo Switch',
          'Wii U',
          'Wii',
          'PC',
          'Mac',
          'Nintendo 3DS & 2DS',
          'Nintendo DS',
          'PlayStation Vita',
          'Sony PSP',
          'Retro Gaming & Microconsoles',
          'Accessories',
          'Digital Games',
          'Kids & Family',
        ],
      },
    };
  },
  getters: {
    getDefaultCategory(state){
      return state.categories[0];
    },
    getDefaultSubCategories(state) {
      return state.subCategories['electronics'];
    },
    getDistricts(state) {
      return state.districts;
    },
    getCategories(state) {
      return state.categories;
    },
    getSubCategories(state) {
      return state.subCategories;
    }
  }
};
